project:
  type: website

website:
  title: "Dipesh Shrestha"
  navbar: 
    left:
      - text: Home
        file: index.qmd
      - text: Blogs
        file: blog.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/dipesh-shrestha-7b90b2187
      - icon: github
        href: https://github.com/shrestha1
      